'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ClientMainPage

    '''<summary>
    '''hlkPersonalInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlkPersonalInfo As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlkUpdateInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlkUpdateInfo As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlkTransaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlkTransaction As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlkSavingDeposit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlkSavingDeposit As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlkSavingsWithdrawal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlkSavingsWithdrawal As Global.System.Web.UI.WebControls.HyperLink
End Class
