'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class StaffMainPage

    '''<summary>
    '''hlkCreateStaffInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlkCreateStaffInfo As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlkViewStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlkViewStaff As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlkNewAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlkNewAccount As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlkViewClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlkViewClient As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlkPropertyApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlkPropertyApplication As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlkViewPropertyLoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlkViewPropertyLoan As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlkPropertyHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlkPropertyHistory As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlkPersonalLoanApp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlkPersonalLoanApp As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlkViewPersonalLoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlkViewPersonalLoan As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlkPersonalHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlkPersonalHistory As Global.System.Web.UI.WebControls.HyperLink
End Class
